# Generated by Django 4.2.6 on 2023-10-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=100)),
                ('Email_Id', models.CharField(max_length=100)),
                ('Phone_No', models.BigIntegerField()),
                ('UserName', models.CharField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
    ]
